### ISSUE TITLE
Is Goodman Cheat Sheet wrong?

### ISSUE THREAD

**Issue by simontorres** [soar-telescope/goodman_pipeline#260]
Red Camera read rate 750 KHz, Analog attn 2, gain 1,47 e-/ADU, Read Noise 5.27.

From the image's header gain is 1,45.

**Comment by simontorres** [comment]
Also, add a clean exit to this

```
01:18:13][C]: Unable to obtain saturation level [core.get_saturation_value:3139]
Traceback (most recent call last):
  File "/user/simon/bin/anaconda3/envs/goodman-v1.2.0/bin/redccd", line 12, in <module>
    GOODMAN_CCD()
  File "/user/simon/bin/anaconda3/envs/goodman-v1.2.0/lib/python3.5/site-packages/goodman_pipeline/images/goodman_ccd.py", line 258, in __call__
    process_images()
  File "/user/simon/bin/anaconda3/envs/goodman-v1.2.0/lib/python3.5/site-packages/goodman_pipeline/images/image_processor.py", line 101, in __call__
    self.create_master_flats(sub_group)
  File "/user/simon/bin/anaconda3/envs/goodman-v1.2.0/lib/python3.5/site-packages/goodman_pipeline/images/image_processor.py", line 445, in create_master_flats
    if self._is_file_saturated(ccd=ccd):
  File "/user/simon/bin/anaconda3/envs/goodman-v1.2.0/lib/python3.5/site-packages/goodman_pipeline/images/image_processor.py", line 129, in _is_file_saturated
    ccd=ccd))])
TypeError: unorderable types: float() > NoneType()
```

**Comment by simontorres** [comment]
This line also apparently has changed 

```python
 ['Red', 750, 0, 3.77, 8.99, 27188, False]]
```

Should be, according to an image header.:

```diff
- ['Red', 750, 0, 3.77, 8.99, 27188, False]]
+ ['Red', 750, 0, 3.78, 8.99, 27188, False]]
```

**Comment by simontorres** [comment]
The values are changing for reasons still not understood for me. Closing this issue now, feel free reopen.
