### ISSUE TITLE
ImportError: cannot import name `_validate_lengths`

### ISSUE THREAD

**Issue by simontorres** [soar-telescope/goodman_pipeline#302]
# Description
This problem appeared most likely after I installed a library (don't remember exactly which one) from a jupyter notebook. I suspect is the new numpy version `1.17.0` but I haven't really tried to trace the real root of the problem. Travis is working OK so I think I just introduced an inconsistency in the virtual environment.

# Full traceback

```[11:19:50][   DEBUG]: Found reference lamp: goodman_comp_400M2_GG455_HgArNe.fits [wavelength._automatic_wavelength_solution:365]
Traceback (most recent call last):
  File "/user/simon/development/soar/goodman_pipeline/goodman_pipeline/scripts/redspec", line 12, in <module>
    GOODMAN_SPECTROSCOPY()
  File "/user/simon/development/soar/goodman_pipeline/goodman_pipeline/spectroscopy/redspec.py", line 288, in __call__
    background_threshold=self.args.background_threshold)
  File "/user/simon/development/soar/goodman_pipeline/goodman_pipeline/spectroscopy/redspec.py", line 517, in _run
    object_number=object_number)
  File "/user/simon/development/soar/goodman_pipeline/goodman_pipeline/spectroscopy/wavelength.py", line 207, in __call__
    corr_tolerance=self.cross_corr_tolerance)
  File "/user/simon/development/soar/goodman_pipeline/goodman_pipeline/spectroscopy/wavelength.py", line 381, in _automatic_wavelength_solution
    intensity=reference_lamp_ccd.data)
  File "/user/simon/development/soar/goodman_pipeline/goodman_pipeline/spectroscopy/wavelength.py", line 666, in _bin_reference_data
    np.mean)
  File "/data/simon/bin/anaconda3/envs/astroconda/lib/python3.5/site-packages/ccdproc/core.py", line 1176, in block_reduce
    data = nddata_utils.block_reduce(ccd, block_size, func)
  File "/data/simon/bin/anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/utils/decorators.py", line 860, in block_reduce
    func = make_function_with_signature(func, name=name, **wrapped_args)
  File "/data/simon/bin/anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/nddata/decorators.py", line 245, in wrapper
    result = func(data, *args, **kwargs)
  File "/data/simon/bin/anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/nddata/utils.py", line 370, in block_reduce
    from skimage.measure import block_reduce
  File "/data/simon/bin/anaconda3/envs/astroconda/lib/python3.5/site-packages/skimage/__init__.py", line 158, in <module>
    from .util.dtype import *
  File "/data/simon/bin/anaconda3/envs/astroconda/lib/python3.5/site-packages/skimage/util/__init__.py", line 7, in <module>
    from .arraycrop import crop
  File "/data/simon/bin/anaconda3/envs/astroconda/lib/python3.5/site-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'

Process finished with exit code 1
```

**Comment by simontorres** [comment]
Updating `scikit-image` from `0.13.0` to `0.15.0` fixes it
